Algoritmo "aj"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Lucas Augusto da SIlva 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 16/08/2022
Var
 nome,cpf:caractere
 i:inteiro



Inicio

  escreval("óla mundo como vcs estao")
  
  para i <-1 ate 15  faca
  
  escreval("Qual seu nome")
  leia(nome)
  escreval("digite seu CPF")
  leia(cpf)
  
  fimpara

Fimalgoritmo