Algoritmo "quadrado"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Lucas Augusto da SIlva 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 15/08/2022
Var
   n1:real
   quadrado:real


Inicio

 escreval("escreva um numero por favor")
 leia(n1)
 
 quadrado<-n1^2
  escreval("o quadrado de", n1, "é",quadrado)


Fimalgoritmo